### ISSUE TITLE
Not possible to generate a Sync Service Instance as described

### ISSUE THREAD

**Issue by hortega** [TwilioDevEd/sdk-starter-java#1]
Executing:
`curl -X POST https://preview.twilio.com/Sync/Services \
 -d 'FriendlyName=MySyncServiceInstance' \
 -u 'SKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:your_api_secret'`

returns HTTP 404 and the following error message:
```json
{"code": 20404, "message": "The requested resource /Sync/Services was not found", "more_info": "https://www.twilio.com/docs/errors/20404", "status": 404}
```

The key and secret supplied in **-u** are the ones created on https://github.com/TwilioDevEd/sdk-starter-java#configure-account-information

**Comment by acamino** [comment]
The same here. You should request access to Sync, then you'll be able to use this product.
https://www.twilio.com/console/form/sync-access
